image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

environment:
  matrix:
    - db: MySQL

    - db: PostgreSQL

for:
  -
    matrix:
      only:
        - db: MySQL

    install:
      - sleep 20
      - java -jar ./artifacts/aqa-shop/aqa-shop.jar --spring.datasource.url=jdbc:mysql://localhost:3306/app &
      - sleep 20

    build_script:
      - chmod +x gradlew
      - ./gradlew test --info -Dselenide.headless=true -DdbUrl=jdbc:mysql://localhost:3306/app


  -
    matrix:
      only:
        - db: PostgreSQL

    install:
      - sleep 20
      - java -jar ./artifacts/aqa-shop/aqa-shop.jar --spring.datasource.url=jdbc:postgresql://localhost:5432/app &
      - sleep 20

    build_script:
      - chmod +x gradlew
      - ./gradlew test --info -Dselenide.headless=true -DdbUrl=jdbc:postgresql://localhost:5432/app
