image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

environment:
  matrix:
    only:
      - db: PostgreSQL

    install:
      - chmod +x gradlew
      - docker-compose version
      - docker-compose build
      - docker-compose up -d &
      - sleep 130
      - java "-Dspring.datasource.url=jdbc:postgresql://localhost:5432/app" "-Dspring.datasource.username=app" "-Dspring.datasource.password=pass" -jar artifacts/aqa-shop.jar &
      - sleep 130

    build_script:
      - chmod +x gradlew
      - ./gradlew test --info -Dselenide.headless=true -DdbUrl=jdbc:postgresql://localhost:5432/app
      - docker-compose down