image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off
environment:
  matrix:
    - db: MySQL

    - db: PostgreSQL

for:
  - matrix:
      only:
        - db: MySQL

    install:
      - sudo curl -SL https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
      - sudo chmod +x /usr/local/bin/docker-compose
      - sudo docker-compose -f /Users/1/IdeaProjects/DiplomaAvdeevFQA43/docker-compose.yml up -d
      - sleep 20
      - java "-Dspring.datasource.url=jdbc:mysql://localhost:3306/app" "-Dspring.datasource.username=app" "-Dspring.datasource.password=pass" -jar artifacts/aqa-shop.jar &
      - sleep 20

    build_script:
      - chmod +x gradlew
      - ./gradlew test --info -Dselenide.headless=true -DdbUrl=jdbc:mysql://localhost:3306/app
    after_build:
      - 7z a results.zip build/reports/tests
    artifacts:
      - path: results.zip
    on_failure:
      - 7z a results.zip build/reports/tests
      - appveyor PushArtifact results.zip

  - matrix:
      only:
        - db: PostgreSQL

    install:
      - chmod +x gradlew
      - docker-compose version
      - docker-compose build
      - docker-compose up &
      - sleep 20
      - java "-Dspring.datasource.url=jdbc:postgresql://localhost:5432/app" "-Dspring.datasource.username=app" "-Dspring.datasource.password=pass" -jar artifacts/aqa-shop.jar &
      - sleep 20

    build_script:
      - chmod +x gradlew
      - ./gradlew test --info -Dselenide.headless=true -DdbUrl=jdbc:postgresql://localhost:5432/app
    after_build:
      - 7z a results.zip build/reports/tests
    artifacts:
      - path: results.zip
    on_failure:
      - 7z a results.zip build/reports/tests
      - appveyor PushArtifact results.zip