image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

environment:
  matrix:
    #    - db: MySQL
    - db: PostgreSQL

#for:
#  - matrix:
#      only:
#        - db: MySQL
#
#    install:
#      - chmod +x gradlew
#      - docker-compose version
#      - docker-compose build
#      - docker-compose up -d &
#      - sleep 30
#      - java "-Dspring.datasource.url=jdbc:mysql://localhost:3306/app" "-Dspring.datasource.username=app" "-Dspring.datasource.password=pass" -jar artifacts/aqa-shop.jar &
#      - sleep 30
#
#    build_script:
#      - chmod +x gradlew
#      - ./gradlew test --info -Dselenide.headless=true -DdbUrl=jdbc:mysql://localhost:3306/app
#      - docker-compose down


#  - matrix:
#      only:
#        - db: PostgreSQL

install:
  - chmod +x gradlew
  - docker-compose version
  - docker-compose build
  - docker-compose up -d &
  - sleep 120
  - java "-Dspring.datasource.url=jdbc:postgresql://localhost:5432/app" "-Dspring.datasource.username=app" "-Dspring.datasource.password=pass" -jar artifacts/aqa-shop.jar &
  - sleep 120

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true -DdbUrl=jdbc:postgresql://localhost:5432/app
  - docker-compose down